export const styles = [
  "Academic",
  "Analytical",
  "Argumentative",
  "Business",
  "Casual",
  "Conversational",
  "Creative",
  "Critical",
  "Descriptive",
  "Emotive",
  "Epigrammatic",
  "Epistolary",
  "Expository",
  "Informative",
  "Instructive",
  "Journalistic",
  "Legal",
  "Medical",
  "Metaphorical",
  "Narrative",
  "Persuasive",
  "Poetic",
  "Satirical",
  "Technical",
];

export const tones = [
  "Angry",
  "Anxious",
  "Authoritative",
  "Bitter",
  "Calm",
  "Clinical",
  "Cold",
  "Confident",
  "Contemplative",
  "Cynical",
  "Emotional",
  "Empathetic",
  "Energetic",
  "Excited",
  "Formal",
  "Friendly",
  "Hopeful",
  "Humorous",
  "Informal",
  "Inquisitive",
  "Inspiring",
  "Ironic",
  "Melancholy",
  "Mournful",
  "Nostalgic",
  "Nurturing",
  "Optimistic",
  "Persuasive",
  "Pessimistic",
  "Playful",
  "Polite",
  "Reassuring",
  "Sarcastic",
  "Serious",
  "Sincere",
  "Sympathetic",
  "Tentative",
  "Warm",
];

export const formats = [
  { label: "Default", value: "default" },
  { label: "Concise", value: "Answer as concise as possible" },
  { label: "Step-by-step", value: "Think step-by-step" },
  { label: "Detailed", value: "Answer in painstakingly detail" },
  {
    label: "Layman's terms",
    value: "Answer like I'm five",
  },
];

export const actions = [
  "Paraphrase",
  "Rewrite",
  "Summarize",
  "Explain",
  "Fix Grammar",
  "None",
];

export const characters = [
  "None",
  "Alfie Solomons",
  "April Ludgate",
  "Bertram Gilfoyle",
  "Captain Holt",
  "Eric Cartman",
  "Gregory House",
  "Logan Roy",
  "Michael Scott",
  "Noho Hank",
  "Peter Griffin",
  "Rick Sanchez",
  "Ron Swanson",
  "Ted Lasso",
  "Tom Wambsgans",
];
