export const greets = {
  welcome: "Hello there! How can I be of assistance to you today?",
  missingApiKey:
    "Hi there! Before you begin using the tool, could you please provide your OpenAI API key? It's required to access the features and functionalities of the tool. Thank you!",
};

export const models = [
  "gpt-3.5-turbo",
  "gpt-3.5-turbo-0613",
  "gpt-3.5-turbo-16k",
  "gpt-3.5-turbo-16k-0613",
  "gpt-4",
  "gpt-4-0613",
  "gpt-4-32k",
  "gpt-4-32k-0613",
];

export const styles = [
  "Academic",
  "Analytical",
  "Argumentative",
  "Business",
  "Casual",
  "Conversational",
  "Creative",
  "Critical",
  "Descriptive",
  "Emotive",
  "Epigrammatic",
  "Epistolary",
  "Expository",
  "Inclusive",
  "Informative",
  "Instructive",
  "Journalistic",
  "Legal",
  "Medical",
  "Metaphorical",
  "Narrative",
  "Persuasive",
  "Poetic",
  "Satirical",
  "Technical",
];

export const tones = [
  "Angry",
  "Anxious",
  "Authoritative",
  "Bitter",
  "Calm",
  "Captivating",
  "Cheerful",
  "Clinical",
  "Cold",
  "Compelling",
  "Confident",
  "Contemplative",
  "Convincing",
  "Cynical",
  "Emotional",
  "Empathetic",
  "Energetic",
  "Excited",
  "Exuberant",
  "Formal",
  "Friendly",
  "Happy",
  "Hopeful",
  "Humorous",
  "Informal",
  "Inquisitive",
  "Inspiring",
  "Ironic",
  "Melancholy",
  "Mournful",
  "Negative",
  "Nostalgic",
  "Nurturing",
  "Optimistic",
  "Persuasive",
  "Pessimistic",
  "Playful",
  "Polite",
  "Positive",
  "Reassuring",
  "Sarcastic",
  "Serious",
  "Sincere",
  "Sympathetic",
  "Tentative",
  "Warm",
];

export const formats = [
  { label: "Default", value: "default" },
  { label: "Concise", value: "Answer as concise as possible" },
  { label: "Step-by-step", value: "Think step-by-step" },
  { label: "Detailed", value: "Answer in painstakingly detail" },
  {
    label: "Layman's terms",
    value: "Answer like I'm five",
  },
];

export const actions = [
  "Explain",
  "Fix Grammar",
  "Paraphrase",
  "Rewrite",
  "Summarize",
  "None",
];

export const characters = [
  "None",
  "Alfie Solomons",
  "April Ludgate",
  "Barack Obama",
  "Bertram Gilfoyle",
  "Captain Holt",
  "Eric Cartman",
  "Gregory House",
  "Logan Roy",
  "Michael Scott",
  "Noho Hank",
  "Peter Griffin",
  "Rick Sanchez",
  "Ron Swanson",
  "Steve Jobs",
  "Ted Lasso",
  "Tom Wambsgans",
  "Warren Buffett",
];
